### ISSUE TITLE
Support for dnx projects 

### ISSUE THREAD

**Issue by Yaojian** [xunit/resharper-xunit#58]
While ReSharper do list the xUnit test in its "Unit Test Sessions" window, it fails on running the tests with the error message: System.IO.FileNotFoundException: C:\Yaojian\Projects\FineWork\devel\src\artifacts\bin\FineWork.Web.WebApp.Tests\FineWork.Web.WebApp.Tests.dll

The solution directory is `C:\Yaojian\Projects\FineWork\devel\src`
The project directory (where project.json lives) is `C:\Yaojian\Projects\FineWork\devel\src\tests\FineWork.Web.WebApp.Tests`

With `devent /ReSharper.Internal` option set, the `JetLogs` is:

````
3:27:17 PM.495: 1: Connecting to 127.0.0.1:25302
3:27:17 PM.499: 1: Waiting for tasks.
3:27:17 PM.510: 3: Configuration received: <configuration><runner-paths /><runner-infos><runner-info id="xUnit" code-base="xunitcontrib.runner.resharper.runner.9.1.DLL" type-name="XunitContrib.Runner.ReSharper.RemoteRunner.XunitTaskRunner" /></runner-infos></configuration>
3:27:17 PM.510: 3: Using JetBrains.ReSharper.TaskRunnerFramework.DummyClientController
3:27:17 PM.520: 5:Runner thread: Processing packets
3:27:17 PM.520: 5:Runner thread: <task-start />
3:27:17 PM.520: 5:Runner thread: Executing 1 root tasks
3:27:17 PM.522: 5:Runner thread: Loading TaskRunner xUnit (XunitContrib.Runner.ReSharper.RemoteRunner.XunitTaskRunner) from file:///C:/Users/Yaojian/AppData/Local/JetBrains/Installations/ReSharperPlatformVs14/xunitcontrib.runner.resharper.runner.9.1.DLL
3:27:17 PM.525: 5:Runner thread: <task-start><task task-type="XunitContrib.Runner.ReSharper.RemoteRunner.Tasks.XunitBootstrapTask, xunitcontrib.runner.resharper.runner.9.1, Version=2.0.6.25609, Culture=neutral, PublicKeyToken=null" runnerID="xUnit" id="4a62860e-04a1-4f21-81da-95592f1a2d71" ProjectId="ADA24DBA-9ED3-43BD-93DB-952C9C6F6315" /></task-start>
3:27:17 PM.530: 5:Runner thread: Setting current directory to C:\Yaojian\Projects\FineWork\devel\src\artifacts\bin\FineWork.Web.WebApp.Tests
3:27:17 PM.537: 5:Runner thread: System.ArgumentException: File not found: C:\Yaojian\Projects\FineWork\devel\src\artifacts\bin\FineWork.Web.WebApp.Tests\FineWork.Web.WebApp.Tests.dll
Parameter name: assemblyFileName
3:27:17 PM.538: 5:Runner thread:    at Guard.FileExists(String argName, String fileName)
   at Xunit.XunitFrontController..ctor(String assemblyFileName, String configFileName, Boolean shadowCopy, String shadowCopyFolder, ISourceInformationProvider sourceInformationProvider, IMessageSink diagnosticMessageSink)
   at XunitContrib.Runner.ReSharper.RemoteRunner.TestRunner.GetFrontController(TestEnvironment environment)
   at XunitContrib.Runner.ReSharper.RemoteRunner.TestRunner.Run(XunitTestAssemblyTask assemblyTask)
3:27:17 PM.539: 5:Runner thread: <task-exception type="System.ArgumentException"><task task-type="XunitContrib.Runner.ReSharper.RemoteRunner.Tasks.XunitTestAssemblyTask, xunitcontrib.runner.resharper.runner.9.1, Version=2.0.6.25609, Culture=neutral, PublicKeyToken=null" runnerID="xUnit" id="5fc57f85-fd7c-4506-9347-3981fb15207f" ProjectId="ADA24DBA-9ED3-43BD-93DB-952C9C6F6315" AssemblyLocation="C:\Yaojian\Projects\FineWork\devel\src\artifacts\bin\FineWork.Web.WebApp.Tests\FineWork.Web.WebApp.Tests.dll" /><message>File not found: C:\Yaojian\Projects\FineWork\devel\src\artifacts\bin\FineWork.Web.WebApp.Tests\FineWork.Web.WebApp.Tests.dll
Parameter name: assemblyFileName</message><stack-trace>   at Guard.FileExists(String argName, String fileName)
   at Xunit.XunitFrontController..ctor(String assemblyFileName, String configFileName, Boolean shadowCopy, String shadowCopyFolder, ISourceInformationProvider sourceInformationProvider, IMessageSink diagnosticMessageSink)
   at XunitContrib.Runner.ReSharper.RemoteRunner.TestRunner.GetFrontController(TestEnvironment environment)
   at XunitContrib.Runner.ReSharper.RemoteRunner.TestRunner.Run(XunitTestAssemblyTask assemblyTask)</stack-trace></task-exception>
3:27:17 PM.539: 5:Runner thread: Finished processing packets
3:27:17 PM.539: 5:Runner thread: <task-finish result="Success" />
3:27:17 PM.562: 3: Closing server
````

**Comment by citizenmatt** [comment]
This is a known issue. ReSharper itself doesn't support the execution environment (it runs tests in an external process, and that's not how DNX/asp.net 5 tests are run). Expect to see support as DNX/asp.net5 stabilise and near completion.

**Comment by khellang** [comment]
So this is not actively worked on by the R# team?

**Comment by JamesNK** [comment]
+1

Things to think about:

* Support for non-DNX frameworks in a project.json, e.g. "net45"
* Support for detecting and running tests from multiple frameworks

**Comment by ttrevorr** [comment]
+1

**Comment by stajs** [comment]
+1

**Comment by MiguelAlho** [comment]
+1

**Comment by rick-sanchez** [comment]
+1 probably merge this into https://github.com/xunit/resharper-xunit/issues/38

**Comment by citizenmatt** [comment]
Good point. Closing in favour for #38
