### ISSUE TITLE
InvalidOperationException related to SuppressUnusedXunitTestElements

### ISSUE THREAD

**Issue by ljani** [xunit/resharper-xunit#72]
Hi,

I just upgraded from VS2013, R#8.2 and xunit 1.9.2 to VS2015, ReSharper 9.2RC, xUnit 2.0.0, xUnit runner 2.0.1 and resharper-xunit 2.2.8 and I'm getting following exception (and a few variations) all the time:

```
Could not get the value of the descritor “XunitContrib.Runner.ReSharper.UnitTestProvider.SuppressUnusedXunitTestElements [Singleton, Corrupted]” to show it into the viewable. Component descriptor XunitContrib.Runner.ReSharper.UnitTestProvider.SuppressUnusedXunitTestElements [Singleton, Corrupted] is corrupted and cannot be accessed

--- EXCEPTION #1/2 [InvalidOperationException]
Message = “Component descriptor XunitContrib.Runner.ReSharper.UnitTestProvider.SuppressUnusedXunitTestElements [Singleton, Corrupted] is corrupted and cannot be accessed”
ExceptionPath = Root.InnerException
ClassName = System.InvalidOperationException
HResult = COR_E_INVALIDOPERATION=80131509
Source = JetBrains.Platform.ComponentModel
StackTraceString = “
  at JetBrains.Application.Components.SingletonDescriptor.GetValue()
     at JetBrains.Application.Components.ViewableValueResolver.ViewableComponentDescriptor`1.<>c__DisplayClass1.<View>b__0(Lifetime descriptorLifetime, IComponentDescriptor descriptor)
”

--- Outer ---

--- EXCEPTION #2/2 [LoggerException]
Message = “Could not get the value of the descritor “XunitContrib.Runner.ReSharper.UnitTestProvider.SuppressUnusedXunitTestElements [Singleton, Corrupted]” to show it into the viewable. Component descriptor XunitContrib.Runner.ReSharper.UnitTestProvider.SuppressUnusedXunitTestElements [Singleton, Corrupted] is corrupted and cannot be accessed”
ExceptionPath = Root
ClassName = JetBrains.Util.LoggerException
InnerException = “Exception #1 at Root.InnerException”
HResult = COR_E_APPLICATION=80131600
StackTraceString = “
  at JetBrains.Util.ILoggerEx.Error(ILogger this, Exception ex, String message)
     at JetBrains.Application.Components.ViewableValueResolver.ViewableComponentDescriptor`1.<>c__DisplayClass1.<View>b__0(Lifetime descriptorLifetime, IComponentDescriptor descriptor)
     at JetBrains.Application.Components.ComponentStorage.View[T](Lifetime lifetime, Action`2 viewer)
     at JetBrains.Application.Components.ViewableValueResolver.ViewableComponentDescriptor`1.View(Lifetime lifetime, Action`2 viewer)
     at JetBrains.Application.Components.ViewableValueResolver.ViewableComponentDescriptor`1.View(Lifetime lifetime, Action`2 viewer)
     at JetBrains.ReSharper.Daemon.UsageChecking.UsageAnalyzer..ctor(Lifetime lifetime, IViewable`1 suppressors)
     at JetBrains.ReSharper.Daemon.JavaScript.UsageChecking.JavaScriptUsageCheckingServices..ctor(Lifetime lifetime, IViewable`1 suppressors)
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
     at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     at JetBrains.Application.Extensibility.PartComponentDescriptor.CreateInstanceOf(Type type, IValueResolveContext context)
     at JetBrains.Application.Extensibility.PartComponentDescriptor.CreateInstance(IValueResolveContext context)
     at JetBrains.Application.Components.SingletonDescriptor.CreateInstanceChecked(OnError onError, IComponentContainer container)
     at JetBrains.Application.Components.SingletonDescriptor.GetValue()
     at JetBrains.Application.Components.InitializationStrategyDefault.Schedule(Lifetime lifetime, IComponentDescriptor dsc)
     at JetBrains.Application.Components.ComponentStorage.InstantiateDescriptors(IEnumerable`1 descriptors)
     at JetBrains.Application.Components.ComponentStorage.ComposeDescriptors(ICollection`1 descriptors)
     at JetBrains.Application.Components.ComponentStorage.Compose()
     at JetBrains.Application.Extensibility.SplittedComponentContainer`2.InitializeDefinition(Lifetime lifetime, TDefinition definition, IPartsCatalogueSet catalogueSet, IComponentContainer parentContainer)
     at JetBrains.ReSharper.Psi.LanguageManager.InitializeDefinition(Lifetime lifetime, PsiLanguageType definition, IPartsCatalogueSet catalogueSet, IComponentContainer parentContainer)
     at JetBrains.Application.Extensibility.SplittedComponentContainer`2.<>c__DisplayClass5.<.ctor>b__2(Lifetime definitionLifetime, TDefinition definition)
     at JetBrains.DataFlow.ViewableCollection`1.View(Lifetime viewLifetime, TValue value, Action`2 observer)
     at JetBrains.DataFlow.ViewableCollection`1.<>c__DisplayClass2.<View>b__1(TValue value)
     at JetBrains.Util.CollectionUtil.ForEach[T](IEnumerable`1 collection, Action`1 action)
     at JetBrains.DataFlow.ViewableCollection`1.View(Lifetime lifetime, Action`2 viewer)
     at JetBrains.ReSharper.Psi.Languages.View(Lifetime lifetime, Action`2 viewer)
     at JetBrains.Application.Extensibility.SplittedComponentContainer`2..ctor(Lifetime lifetime, IPartsCatalogueSet catalogueSet, IComponentContainer parentContainer, IViewable`1 definitions, Expression`1 property)
     at JetBrains.ReSharper.Psi.LanguageManager..ctor(IShellLocks locks, Lifetime lifetime, IPartsCatalogueSet catalogueSet, IComponentContainer parentContainer, ILanguages languages)
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
     at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     at JetBrains.Application.Extensibility.PartComponentDescriptor.CreateInstanceOf(Type type, IValueResolveContext context)
     at JetBrains.Application.Extensibility.PartComponentDescriptor.CreateInstance(IValueResolveContext context)
     at JetBrains.Application.Components.SingletonDescriptor.CreateInstanceChecked(OnError onError, IComponentContainer container)
     at JetBrains.Application.Components.SingletonDescriptor.GetValue()
     at JetBrains.Application.Components.SignatureResolution.BindArguments(List`1 argumentDescriptors, String origin)
     at JetBrains.Application.Extensibility.PartComponentDescriptor.CreateInstanceOf(Type type, IValueResolveContext context)
     at JetBrains.Application.Extensibility.PartComponentDescriptor.CreateInstance(IValueResolveContext context)
     at JetBrains.Application.Components.SingletonDescriptor.CreateInstanceChecked(OnError onError, IComponentContainer container)
     at JetBrains.Application.Components.SingletonDescriptor.GetValue()
     at JetBrains.Application.Components.SignatureResolution.BindArguments(List`1 argumentDescriptors, String origin)
     at JetBrains.Application.Extensibility.PartComponentDescriptor.CreateInstanceOf(Type type, IValueResolveContext context)
     at JetBrains.Application.Extensibility.PartComponentDescriptor.CreateInstance(IValueResolveContext context)
     at JetBrains.Application.Components.SingletonDescriptor.CreateInstanceChecked(OnError onError, IComponentContainer container)
     at JetBrains.Application.Components.SingletonDescriptor.GetValue()
     at JetBrains.Application.Components.InitializationStrategyDefault.Schedule(Lifetime lifetime, IComponentDescriptor dsc)
     at JetBrains.Application.Components.ComponentStorage.InstantiateDescriptors(IEnumerable`1 descriptors)
     at JetBrains.Application.Components.ComponentStorage.ComposeDescriptors(ICollection`1 descriptors)
     at JetBrains.Application.Components.ComponentStorage.Compose()
     at JetBrains.Application.Extensibility.SplittedComponentContainer`2.InitializeDefinition(Lifetime lifetime, TDefinition definition, IPartsCatalogueSet catalogueSet, IComponentContainer parentContainer)
     at JetBrains.Application.Extensibility.SplittedComponentContainer`2.<>c__DisplayClass5.<.ctor>b__2(Lifetime definitionLifetime, TDefinition definition)
     at JetBrains.DataFlow.ViewableCollection`1.View(Lifetime viewLifetime, TValue value, Action`2 observer)
     at JetBrains.DataFlow.ViewableCollection`1.<>c__DisplayClass2.<View>b__1(TValue value)
     at JetBrains.Util.CollectionUtil.ForEach[T](IEnumerable`1 collection, Action`1 action)
     at JetBrains.DataFlow.ViewableCollection`1.View(Lifetime lifetime, Action`2 viewer)
     at JetBrains.ProjectModel.ProjectFileTypes.View(Lifetime lifetime, Action`2 viewer)
     at JetBrains.Application.Extensibility.SplittedComponentContainer`2..ctor(Lifetime lifetime, IPartsCatalogueSet catalogueSet, IComponentContainer parentContainer, IViewable`1 definitions, Expression`1 property)
     at JetBrains.ProjectModel.FileTypes.ProjectFileTypeServices..ctor(Lifetime lifetime, IPartsCatalogueSet catalogueSet, IComponentContainer parentContainer, IProjectFileTypes fileTypes)
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
     at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     at JetBrains.Application.Extensibility.PartComponentDescriptor.CreateInstanceOf(Type type, IValueResolveContext context)
     at JetBrains.Application.Extensibility.PartComponentDescriptor.CreateInstance(IValueResolveContext context)
     at JetBrains.Application.Components.SingletonDescriptor.CreateInstanceChecked(OnError onError, IComponentContainer container)
     at JetBrains.Application.Components.SingletonDescriptor.GetValue()
     at JetBrains.Application.Components.SignatureResolution.BindArguments(List`1 argumentDescriptors, String origin)
     at JetBrains.Application.Extensibility.PartComponentDescriptor.CreateInstanceOf(Type type, IValueResolveContext context)
     at JetBrains.Application.Extensibility.PartComponentDescriptor.CreateInstance(IValueResolveContext context)
     at JetBrains.Application.Components.SingletonDescriptor.CreateInstanceChecked(OnError onError, IComponentContainer container)
     at JetBrains.Application.Components.SingletonDescriptor.GetValue()
     at JetBrains.Application.Components.EnumerableValueResolver.EnumerableComponentDescriptor`1.<GetEnumerator>d__0.MoveNext()
     at JetBrains.Application.Components.EnumerableValueResolver.EnumerableComponentDescriptor`1.GetValue()
     at JetBrains.Application.Components.SignatureResolution.BindArguments(List`1 argumentDescriptors, String origin)
     at JetBrains.Application.Extensibility.PartComponentDescriptor.CreateInstanceOf(Type type, IValueResolveContext context)
     at JetBrains.Application.Extensibility.PartComponentDescriptor.CreateInstance(IValueResolveContext context)
     at JetBrains.Application.Components.SingletonDescriptor.CreateInstanceChecked(OnError onError, IComponentContainer container)
     at JetBrains.Application.Components.SingletonDescriptor.GetValue()
     at JetBrains.Application.Components.DelayedInitializationStrategy.<>c__DisplayClass5.<Schedule>b__0()
     at JetBrains.Application.Components.DelayedInitializationStrategy.<>c__DisplayClassb.<Dispatch>b__a()
     at JetBrains.Util.Logging.Logger.Catch(Action action)
     at JetBrains.Application.Components.DelayedInitializationStrategy.<Dispatch>b__9()
     at JetBrains.Threading.ReentrancyGuard.Execute(String name, Action action)
     at JetBrains.Threading.ReentrancyGuard.ExecuteOrQueue(String name, Action action, TaskPriority priority)
     at JetBrains.Application.Components.DelayedInitializationStrategy.<Dispatch>b__8()
     at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
     at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
     at System.Windows.Threading.DispatcherOperation.InvokeImpl()
     at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Windows.Threading.DispatcherOperation.Invoke()
     at System.Windows.Threading.Dispatcher.ProcessQueue()
     at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
     at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
     at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
     at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
     at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
     at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
     at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
”
```

The solution is set to use x86 and .NET Framework 4.5.1.

The exception goes away if I uninstall this extension and VS is able to execute the tests, but I'd prefer ReSharper.

Is this a problem with the ReSharper RC, this extension or did I do something wrong when updating? The previous setup worked just fine.

**Comment by ljani** [comment]
Oh and I'm on Windows 10 whereas I was previously on Windows 8.1.

It seems I can run tests, but they won't produce any output whenever or not the test failed.

**Comment by ljani** [comment]
Nevermind for the exception, it was my bad. I managed to download the ReSharper RC1 by accident, but updating to RC3 fixes the issue.

I'm not still getting any output in the runner, but I haven't searched for any solutions with that so I'll close this ticket.

**Comment by ljani** [comment]
I went home and thus rebooted my computer and the output is fine now. I had previously only restarted VS multiple times. A break is always good for you I guess.

**Comment by ljani** [comment]
I was a little too eager with that comment. The first test run went fine and now I can't even run the test. They only show up with the blue and white question mark icon. The second run said that the tests had failed, but had no output.

**Comment by ljani** [comment]
9.2 final seems to be out and everything is okay now. Sorry for wasting your time.
